#!/usr/bin/bash
#Tools SadapWhatsApp
#Sadap WhatsApp
#By AC1L W4S H3R3
#Jangan DiRecord Tod!!!
#Bersihkan Layar
clear
blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
echo " "
echo  $blue "<|======================================|>"
echo  $blue "<|            Tools SadapWhatsApp       |>"
echo  $blue "<|                                      |>"
echo  $blue "<| Name: AC1LD4Y    ||    AC1LD4Y       |>"
echo  $blue "<| MyTeam: AC1LH3R33 Cyber Team         |>"
echo  $blue "<| Contact: +6285280645068              |>"
echo  $blue "<| Thanks To: MUHAMMAD 4SR1L S34N.      |>"
echo  $blue "<|======================================|>"
sleep 1
echo  $red "============== $red MENU $green ================="
echo $blue "================================================="
echo $blue "|| $pur   1. Sadap WhatsApp No Indosat   $blue ||"
echo $blue "|| $i     2. Sadap WhatsApp No Telkomsel $me  ||"
echo $blue "|| $pu    3. Sadap WhatsApp No XL / Axis $cy  ||"
echo $blue "|| $cy    4. Sadap WhatsApp No 3(Three)  $i   ||"
echo $blue "|| $me    5. Sadap Kontol Gan            $me ||"
echo $blue "|| $green 0. Exit Sadap WhatsApp         $me  ||"
echo $blue "================================================="
echo $blue"╭──[Masukkan Pilihan Anda]>"
read -p"╰───────root@AC1LD4Y=•>" AC1LD4Y;
if [ $MrTamfanX = 1 ] || [ $AC1LD4Y = 01 ]
then
echo $blue"╭──[Silahkan Masukan Nomernya]>"
read -p"╰───────root@AC1LD4Y=•>" AC1LD4Y;
sleep 2
echo $red "[+]Scaning...."
sleep 3
echo $blue "10%"
sleep 4
echo $green "20%"
sleep 2
echo $cyan "30%"
sleep 8
echo $purple "40%"
sleep 3
echo $blue "50%"
sleep 2
echo $red "60%"
sleep 5
echo $green "70%"
sleep 6
echo $cyan "80%"
sleep 7
echo $purple "90%"
sleep 3
echo $blue "100%"
sleep 2
echo $green "Prosessing Done"
sleep 4
echo  $blue "Nomer WhatsApp Berhasil Di Sadap $Verifikasi"fi
fi

if [ $AC1LD4Y = 2 ] || [ $AC1LD4Y = 02 ]
then
echo $blue"╭──[Silahkan Masukan Nomernya]>"
read -p"╰───────root@AC1LD4Y=•>" AC1LD4Y;
sleep 2
echo $red "[+]Scaning...."
sleep 5
echo $blue "10%"
sleep 3
echo $green "20%"
sleep 8
echo $cyan "30%"
sleep 3
echo $purple "40%"
sleep 6
echo $blue "50%"
sleep 5
echo $red "60%"
sleep 4
echo $green "70%"
sleep 6
echo $cyan "80%"
sleep 8
echo $purple "90%"
sleep 6
echo $blue "100%"
sleep 9
echo $green "Prosessing Done"
sleep 3
echo  $blue "Nomer WhatsApp Berhasil Di Sadap $Verifikasi"
fi

if [ $AC1LD4Y = 3 ] || [ $AC1LD4Y = 03 ]
then
echo $blue"╭──[Silahkan Masukan Nomernya]>"
read -p"╰───────root@AC1LD4Y=•>" AC1LD4Y;
sleep 2
echo $red "[+]Scaning...."
sleep 8
echo $blue "10%"
sleep 4
echo $green "20%"
sleep 5
echo $cyan "30%"
sleep 6
echo $purple "40%"
sleep 4
echo $blue "50%"
sleep 2
echo $red "60%"
sleep 3
echo $green "70%"
sleep 9
echo $cyan "80%"
sleep 7
echo $purple "90%"
sleep 4
echo $blue "100%"
sleep 9
echo $green "Prosessing Done"
sleep 9
echo  $blue "Nomer WhatsApp Berhasil Di Sadap $Nomer $Kode Verifikasi"
fi

if [ $AC1LD4Y = 4 ] || [ $AC1LD4Y = 04 ]
then
echo $blue"╭──[Silahkan Masukan Nomernya]>"
read -p"╰───────root@AC1LD4Y=•>" AC1LD4Y;
sleep 2
echo $red "[+]Scaning...."
sleep 8
echo $blue "10%"
sleep 7
echo $green "20%"
sleep 5
echo $cyan "30%"
sleep 4
echo $purple "40%"
sleep 5.5
echo $blue "50%"
sleep 4
echo $red "60%"
sleep 5
echo $green "70%"
sleep 6
echo $cyan "80%"
sleep 7
echo $purple "90%"
sleep 5
echo $blue "100%"
sleep 3
echo $green "Prosessing Done"
sleep 4
echo  $blue "Nomer WhatsApp Berhasil Di Sadap $Nomer $Kode Verifikasi"
fi

if [ $AC1LW3SH3R3 = 0 ] || [ $AC1LW4SH3R3 = 00 ]
then
echo  $red "Bye Bye Sayang"
echo  $blue "Jangan Lupa Harus Ngeue Kalo Bisa!"
echo  $green "MrTamfanX Cyber Team!"
exit
fi
